### ISSUE TITLE
Unable to run jar file

### ISSUE THREAD

**Issue by Faansuu** [stephanebruckert/JMines#1]
I'm a noob and I don't know how to run the .jar file. Can you tell me exactly what to do to run this game? Thanks, I'll appreciate it alot!

**Comment by stephanebruckert** [comment]
Sorry for the late response, I just saw you opened an issue...

You should be able to download the .jar file from https://github.com/stephanebruckert/JMines/releases, then open your terminal, go to the same directory as where the .jar is, and run the commands you see in the README https://github.com/stephanebruckert/JMines/blob/master/README.md.

This assumes you have Java installed, let me know if you see any error message

**Comment by stephanebruckert** [comment]
Hi @Faansuu, sorry for the late response, I just saw you opened an issue...

Assuming you have Java installed on your machine, you should be able to download the .jar file from https://github.com/stephanebruckert/JMines/releases, then open your terminal, go to the same directory as where the .jar is, and run the 2 commands you see in the README https://github.com/stephanebruckert/JMines/blob/master/README.md:

 - `java -cp targets/JMines-1.0.0.jar server.RunServer`
 - `java -cp targets/JMines-1.0.0.jar client.RunClient`

which should open the game.

Let me know if you see any error message or where it's blocking

**Comment by Faansuu** [comment]
Hi @stephanebruckert , thanks for replying hehe, but can I do this on Windows instead? I just realized you're using macOS.

**Comment by stephanebruckert** [comment]
I haven't tried it, but hopefully it's not too different. Assuming you have downloaded the .jar into your user's `Downloads` directory:

 - open the command/terminal: `Windows` + R, then type `cmd.exe`
 - then move to the right directory:
   - to your user directory, type `cd %HOMEPATH%`
   - then move to `Downloads`, type `cd Downloads`
 - type the same java commands as on mac

**Comment by Faansuu** [comment]
I get these errors.
Error: Could not find or load main class server.RunServer
Error: Could not find or load main class client.RunClient

Also I do have Java 8 installed if that's necessary.

**Comment by stephanebruckert** [comment]
Ha, probably you need to remove `targets/` before the jar name in both commands.

Also, when running the client, you can use `localhost` as the server IP, since you are likely going to run the client and server on the same machine.

**Comment by Faansuu** [comment]
Sweet it worked! How do I use server ip to play with my friend?

**Comment by stephanebruckert** [comment]
Great! Assuming you are still running the server and you opened the client using `localhost`, your friend will be able to start a client using your IP instead of localhost. Two possibilities:

 - if you are on the same local network (i.e. school, home), find your local IP by typing `ipconfig` in the command line and [look for "Wi-Fi" / "IPv4"](https://www.groovypost.com/howto/find-windows-10-device-ip-address/),
 - if you want to play over the internet, get [your public IP](https://www.google.com/search?q=my%20ip) from Google.

The first option should work without problem, while the second one will only work if no firewall is blocking the way (port 1099) 🤞

**Comment by Faansuu** [comment]
Option 1 with the local ip seems to be working, but it doesn't work using my public ip. I have opened port 1099 within Windows Firewall and still no success. 

Also I tried this following command line "**netstat -ano | findstr -i SYN_SENT**" 
to see if there are firewalls blocking the port or not, but nothing returned.

Thanks for taking the time to help! I appreciate it. This game just brings back so many fun memories.

**Comment by stephanebruckert** [comment]
It could be your router that has a firewall and blocks the port. Or your friend's. So you can try to either configure your router, or try with your phone's hotspot, which might not block any port.

Just in case... if you are are on the same local network as your friend, know that you won't be able to use your public IP, since you both have the same.

Wishing you luck with that.

> Thanks for taking the time to help! I appreciate it. This game just brings back so many fun memories.

Yes, good times...
